import org.apache.hadoop.security.protocolPB.RefreshUserMappingsProtocolServerSideTranslatorPB;
public class FunctionUse3398 {
public void funcUse() {
RefreshUserMappingsProtocolServerSideTranslatorPB refreshusermappingsprotocolserversidetranslatorpb = new RefreshUserMappingsProtocolServerSideTranslatorPB();
refreshusermappingsprotocolserversidetranslatorpb.refreshSuperUserGroupsConfiguration(null,null);
}
}